name: Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.js'
      - '**.json'
      - '.github/workflows/**'
      - 'package.json'
      - 'tests/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.js'
      - '**.json'
      - '.github/workflows/**'
      - 'package.json'
      - 'tests/**'

# Cancel in-progress runs when a new workflow with the same ref is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Add timeout to match our local test timeout
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1 # Shallow clone for faster checkout
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm' # Enable built-in npm caching
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      
    - name: Run tests
      run: npm run test:ci